name: eb_clean_cli
description: A Complete CLI app to create and generate project templates inspired by very_good_cli
version: 0.0.1-dev.21+1
homepage: https://github.com/kishor98100/eb_clean_cli
#publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  path: ^1.8.3
  args: ^2.3.2
  glob: ^2.1.1
  mason: ^0.1.0-dev.41
  mason_logger: ^0.2.4
  meta: ^1.9.0
  pubspec_parse: ^1.2.1
  universal_io: ^2.0.4
  usage: ^4.1.0
  recase: ^4.1.0
  pub_updater: ^0.2.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.0
  build_version: ^2.1.1
  build_runner: ^2.3.3
executables:
  eb_clean:

false_secrets:
  - lib/src/**/**_bundle.dart
