name: eb_clean_cli
description: A Complete CLI app to create and generate project templates inspired by very_good_cli
version: 0.0.1-dev.13
homepage: https://github.com/kishor98100/eb_clean_cli
#publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.1
  args: ^2.1.0
  glob: ^2.0.2
  mason: ^0.1.0-dev.21
  mason_logger: ^0.1.0-dev.12
  meta: ^1.3.0
  pubspec_parse: ^1.2.0
  universal_io: ^2.0.4
  usage: ^4.0.2
  recase: ^4.0.0

  pub_updater: ^0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
executables:
  eb_clean:

false_secrets:
  - lib/src/**/**_bundle.dart
